name: Metrics Daily DevOps & .NET

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Detailed PageSpeed report
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.dailydevops.pagespeed.svg
          token: NOT_NEEDED
          base: ""
          committer_message: Update ${filename} [skip ci]
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://daily-devops.net

      - name: News from Daily DevOps & .NET
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.dailydevops.rss.svg
          token: NOT_NEEDED
          base: ""
          committer_message: Update ${filename} [skip ci]
          plugin_rss: yes
          plugin_rss_source: http://daily-devops.net/en/feed.rss
          plugin_rss_limit: 10